FROM library/postgres:9.6

RUN apt-get update \
    && apt-get install -y \
    --no-install-recommends \
      postgis \
      postgresql-9.6-postgis-2.3 \
      postgresql-contrib-9.6 \
      postgresql-9.6-postgis-scripts \
      postgresql-server-dev-9.6 \
      pgtop \
    && apt-get clean \
    && apt-get autoremove \
    && rm -r /var/lib/apt/lists/*

COPY docker-entrypoint-initdb.d /docker-entrypoint-initdb.d

RUN dpkg-query -l postgis

RUN ls -lAh /usr/share/postgresql/9.6/extension/postgis*

RUN echo "listen_addresses='*'" >> /var/lib/postgresql/data/postgresql.conf
